---
apiVersion: v1
kind: Secret
metadata:
  name: credentials
type: kubernetes.io/Opaque
data:
  mysql-root-password: WlZ5V3B2aGV4Zld5b25mRm5FdmJCb3pDZ0NoeWpvS0xnaQ==
  mysql-password: WlZ5V3B2aGV4Zld5b25mRm5FdmJCb3pDZ0NoeWpvS0xnaQ==
  finnhub_api_key: YzJkdXM5YWFkM2llZmRvNm0xdDA=
