---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trading-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trading-app
  template:
    metadata:
      labels:
        app: trading-app
    spec:
      containers:
      - name: trading-real-time
        image: gcr.io/trading-309422/trading-real-time:1.0.0
        env:
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: credentials
              key: mysql_password
        - name: FINNHUB_API_KEY
          valueFrom:
            secretKeyRef:
              name: credentials
              key: finnhub_api_key
      - name: trading-historical
        image: gcr.io/trading-309422/trading-historical:1.0.0
        env:
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: credentials
              key: mysql_password
        - name: FINNHUB_API_KEY
          valueFrom:
            secretKeyRef:
              name: credentials
              key: finnhub_api_key
      - name: trading-ui
        image: gcr.io/trading-309422/trading-ui:1.0.0
        env:
        - name: DB_PASS
          valueFrom:
            secretKeyRef:
              name: credentials
              key: mysql_password
        - name: FINNHUB_API_KEY
          valueFrom:
            secretKeyRef:
              name: credentials
              key: finnhub_api_key
        ports:
        - containerPort: 8080